---
- name: Change User Primary Group
  hosts: all
  become: true
  vars:
    myuser: "example"
    mygroup: "users"
  tasks:
    - name: change primary group
      ansible.builtin.user:
        name: "{{ myuser }}"
        group: "{{ mygroup }}"