---
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Define Vars
  include_tasks: define_vars.yml

- name:          Install WebSphere Application Server - Fixes
  include_tasks: install_was_fixes.yml
  when:          version_already_installed.rc != 0
