---
- name:          Setup Operating System
  include_tasks: setup_os.yml

- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Define Vars
  include_tasks: define_vars.yml

- name:          Install IBM HTTP Server
  include_tasks: install_ihs.yml
  when:          version_already_installed.rc != 0
