---
- name:              Cleanup Binaries directory
  file:              path={{ __tmp_dir }}/{{ item }} state=absent
  ignore_errors:     true
  with_items:
    - "cnx"
    - "cnx-cr"
    - "CTemp"

- name:              Create Binaries directory
  file:              path={{ __tmp_dir }}/{{ item }} state=directory mode=0755
  with_items:
    - "cnx"
    - "cnx-cr"
    - "CTemp"

- name:              Create Logs directory
  file:              path={{ __logs_dir }} state=directory mode=0755

- name:              Download Installer
  get_url:
    url:             "{{ cnx_repository_url }}/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/cnx/{{ item.file_name }}"
    mode:            0755
    checksum:        sha256:{{ item.check_sum }}
  with_items:        "{{ __cnx_files }}"

- name:              Extract Installer
  unarchive:
    src:             "{{ __tmp_dir }}/cnx/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/cnx/"
    copy:            no
  with_items:        "{{ __cnx_files }}"

- name:              Download Installer CCM
  get_url:
    url:             "{{ cnx_repository_url }}/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/cnx/{{ item.file_name }}"
    mode:            0755
    checksum:        sha256:{{ item.check_sum }}
  with_items:        "{{ __ccm_files }}"
  when:              (ccm_install is defined)

- name:              "Download Installer Connections CR Fixes"
  get_url:
    url:             "{{ cnx_fixes_repository_url }}/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/cnx-cr/{{ item.file_name }}"
    mode:            0755
    checksum:        sha256:{{ item.check_sum }}
  with_items:        "{{ __cnx_fixes_files }}"
  when:             (cnx_fixes_version is defined)

- name:              "Extract Installer Connections CR Fixes"
  unarchive:
    src:             "{{ __tmp_dir }}/cnx-cr/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/cnx-cr/"
    copy:            no
  with_items:        "{{ __cnx_fixes_files }}"
  when:             (cnx_fixes_version is defined)