---
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Setup Operating System
  include_tasks: setup_os.yml

- name:          Define Vars
  include_tasks: define_vars.yml

- name:          Download and Extract Connections Files
  include_tasks: download_extract_connections.yml
  when:          version_already_installed.rc != 0

- include_tasks: install_connections.yml
  when:          version_already_installed.rc != 0


