# Delete directories - BE CAREFULL
#
# ansible-playbook -i environments/hosts.development -u <username> -k playbooks/ibm-was-nd/was-delete-all.yml
---
- hosts:                    dmgr,was_servers
  become:                   true
  tasks:
    - name:          KillAll Java
      command:       killall -9 java
      register:      cout
      #with_items:
      #- "{{ __ibm_dir }}/Connections"
      ignore_errors: true

    - name:                  "Cleanup All directories"
      file:
        path:                "{{ item }}"
        state:               absent
      with_items:
        - /var/ibm
        - /opt/IBM/Binaries
        - /opt/IBM/InstallationManager
        - /opt/IBM/WebSphere
        - /opt/IBM/IMShared
        - /etc/.ibm

    - name:        Delete Connections directory
      file:
        path:                "{{ item }}"
        state:               absent
      with_items:
        - "/opt/IBM/Connections"
        - "/opt/IBM/CTemp"
        - "/var/.com.zerog.registry.xml"
        - "/root/.InstallAnywhere"
        - "/root/.java"
      ignore_errors: true

- hosts:                    ihs_servers
  become:                   true
  tasks:
    - name:          KillAll Java
      command:       killall -9 httpd
      register:      cout
      #with_items:
      #- "{{ __ibm_dir }}/Connections"
      ignore_errors: true

    - name:                  "Cleanup All directories"
      file:
        path:                "{{ item }}"
        state:               absent
      with_items:
        - /var/ibm
        - /opt/IBM/Binaries
        - /opt/IBM/InstallationManager
        - /opt/IBM/HTTPServer
        - /opt/IBM/WebSphere
        - /opt/IBM/IMShared
        - /etc/.ibm
        - /root/.ibm