---
- name:          Cleanup Backup directory
  file:          path={{ __bkp_dir }} state=absent
  ignore_errors: true

- name:          Create Backup directory
  file:          path={{item}} state=directory mode=0755
  with_items:
    - "{{ __bkp_dir }}"

- name:          Backup Directories
  archive:
    path:         "{{item.dir}}"
    dest:         "{{ __bkp_dir }}/{{item.zipfile}}"
    format: zip
  with_items:
  - { dir: "{{ __ibm_dir }}/InstallationManager", zipfile: "installation_manager.zip" }
  - { dir: "{{ __ibm_dir }}/IMShared", zipfile: "imshared.zip" }
  - { dir: "{{ __ibm_dir }}/WebSphere", zipfile: "websphere.zip" }
  - { dir: "/var/ibm", zipfile: "var_ibm.zip" }
  - { dir: "/etc/.ibm", zipfile: "etc_ibm.zip" }

- name:          Backup Connections Directories
  archive:
    path:         "{{item.dir}}"
    dest:         "{{ __bkp_dir }}/{{item.zipfile}}"
    format: zip
  with_items:
  - { dir: "{{ __ibm_dir }}/Connections", zipfile: "connections.zip" }
  ignore_errors: true

- name:          Backup Files
  command:       cp {{item}} {{item}}_{{ __now }}
  with_items:
  - /var/ibm/InstallationManager/installed.xml
  - /var/ibm/InstallationManager/installRegistry.xml
  - /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
  register:      cout

- name:          Disable Repository on Installation Manager
  replace:
    path:        /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
    regexp:      '(\s*)RepositoryIsOpen=true(\s*)'
    replace:     '\1RepositoryIsOpen=false\2'
    backup:      yes
  ignore_errors: true
