---
- name: VM info
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  vars_prompt:
    - name: username
      prompt: username
      private: false
    
    - name: password
      prompt: password

  tasks:
    - name: get VM info
      vmware_guest_info:
        hostname: ""
        username: "{{ username }}"
        password: "{{ password }}"
        datacenter: ""
        validate_certs: false
        name: ""
      register: detailed_vm_info

    - name: print VM info
      ansible.builtin.debug:
        var: detailed_vm_info
        