---
- name: git module demo
  hosts: localhost
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
      become: true

    - name: checkout git repo
      ansible.builtin.git:
        repo: https://github.com/lucab85/ansible-pilot.git
        dest: /home/devops/ansible-pilot
