---
- name: Read an environment variable
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: display HOME
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'HOME') }}"
  
