---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
cluster_name: "production"
vm_name: "myvm"
vcenter_destination_folder: "myvm"
vm_template: "mytemplate"
vm_state: "poweroff"
