# Install Connections 6
---
- name:                    Install WAS Servers
  hosts:                   dmgr,was_servers
#  serial:                  1
  become:                  true
  roles:
    - roles/installation-manager-install
    - roles/was-nd-install
    - roles/was-nd-fix-install
    #- roles/was-java-install     # Java 8.5.0.17 already available with WAS 8.5.5.14
    - roles/db2-jdbc-driver-install

- name:                    Install HTTP Servers
  hosts:                   ihs_servers
  become:                  true
  roles:
    - roles/installation-manager-install
    - roles/ibm-http-server-install
    - roles/ibm-http-server-fix-install
    - roles/ibm-http-config-plgwct
    - roles/ibm-http-adminctl-restart
    - roles/ibm-http-server-restart

- name:                    Setup DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/was-dmgr-create-profile
    - roles/was-dmgr-start
    - roles/was-dmgr-import-tls-cert
    - roles/was-dmgr-config-ldap
    - roles/was-dmgr-config-jvm
    - roles/was-dmgr-enable-app-sec
    - roles/was-dmgr-restart

- name:                    Setup WAS Nodes
  hosts:                   was_servers
  serial:                  1
  become:                  true
  roles:
    - roles/was-profile-create
    - roles/was-nodeagent-start

- name:                    Setup HTTP Servers on DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/was-dmgr-config-webserver

- name:                    Setup Connections
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/connections-install
