---
- name: cron module demo
  hosts: localhost
  tasks:
    - name: "example cronjob"
      ansible.builtin.cron:
        name: "test"
        state: present
        minute: "*/2"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: 'logger "Supriyo Sarkar"'
