---
- name: remote synchronize
  hosts: all
  become: false
  vars:
    source: 'path to file'
    destn: 'destination path'
  tasks:
    - name: rsync installed
      ansible.builtin.package:
        name: rsync
        state: present
      become: true
    
    - name: data synchronzation
      ansible.posix.synchronize:
        src: "{{ source }}"
        dest: "{{ destn }}"